# Generated by Django 5.0.7 on 2024-08-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='getresult',
            name='user_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
