# Generated by Django 5.0.7 on 2024-08-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths_app', '0002_remove_questions_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetResult',
        ),
    ]
